version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dba_pg
    restart: always
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: dba
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
